# /qompassai/rust/deny.toml
# Qompass AI Deny.toml template
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################### 
[graph]
all-features = true
no-default-features = false

[output]
feature-depth = 1

[advisories]
ignore = []
git-fetch-with-cli = true
[licenses]
allow = [
  "MIT",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-3-Clause",
  "ISC",
]
confidence-threshold = 0.8
exceptions = [
  { allow = ["Unicode-DFS-2016", "Unicode-3.0"], crate = "unicode-ident" },
  { allow = ["NCSA"], crate = "libfuzzer-sys" },
]

[licenses.private]
ignore = true
[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = []
deny = []
skip-tree = []
[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = ["git+https://github.com/rosenpass/memsec.git?branch=master"]
[sources.allow-org]
github = []
gitlab = []
bitbucket = []
